### ISSUE TITLE
GDPR Validation Check

### ISSUE THREAD

**Issue by SchulzeStTSI** [eu-digital-green-certificates/dgc-gateway#107]
The usage of dob, name and UVCI (excepting the usage of the extractUVCI Methode) in the business rules is not allowed, therefore the gateway should implement and content check on the json logic block to avoid that this fields are used. This can be done by scanning for "dob" or ".dob" etc. to ensure that the json block not contains this kind of fields.

**Comment by umma08** [comment]
@On this issue - there are a number of fields that could pose issues under GDPR - the use of UUIDs, for example, (whether as sha256 representation or otherwise) would be classified as personal data given that they can indirectly be used to identify an individual. 

Further to this matter, does @European_Commission/**@ANYBODY** know whether a DPIA has been conducted yet by **any** appropriate DPA for **any** deployment?

**Comment by f11h** [comment]
Waiting for implementation of Logic Validator.
