### ISSUE TITLE
What is the right URL of the official central EC DGCG?

### ISSUE THREAD

**Issue by jbx1** [eu-digital-green-certificates/dgc-gateway#114]
What is the right URL for the central DGCG that will host all the keys to be distributed to the national backends?

The applications here seem to all be pointing to this temporary URL for the ACC environment: 
https://dgca-verifier-service.cfapps.eu10.hana.ondemand.com/signercertificateStatus

But I presume this is not the official DGCG. Some KIDs of some countries are missing. 

The document about the DGCG specifications says that the "DGCG hosting URL to be clarified." (page 17), but it has not been updated since April. 

https://ec.europa.eu/health/sites/default/files/ehealth/docs/digital-green-certificates_v2_en.pdf

Can anyone clarify what the official DGCG URL is? Thanks.

**Comment by daniel-eder** [comment]
The DGCG URL has been distributed to the member states to set up their national backends.
Applications that work with DCCs do not directly access the DGCG - they access the public keys (trustlist) via the national backends.

Third party applications need to get in touch with the government of their member state to organize access to this trustlist, as this access is handled by the member states, there is no global/eu-wide list.

See also https://github.com/eu-digital-green-certificates/dgc-participating-countries/issues/10 

(If this issue is not about public keys to validate DCCs, but rather for a national backend that needs to access the DGCG please comment and we'll reopen, then it's not a duplicate)
