### ISSUE TITLE
question regarding the requirement for connection to the gateway

### ISSUE THREAD

**Issue by SonVuBao** [eu-digital-green-certificates/dgc-gateway#115]
Hi thank you so much for sharing and developing this. 

I have a few question regarding other non-EU countries to connect to the gateway:

First of all, is there any specific requirement regarding technical and audit of the certificate issuer to be able to join in the gateway.

Second, I found that there are supposed to be a technical test for other countries to be able to verify and issue certificate. Could you kindly tell me more about it.

Thank you so much

**Comment by daniel-eder** [comment]
Hi @SonVuBao!

The first step for a non-EU country to connect to the gateway is a political, rather than technical. The governments/responsible stakeholders of countries that want to connect to the system first need to get in touch with the European Commission. If your Government have no point of contact, let me know, and I will assist in getting in touch.

As for the purely technical side (although I would highly encourage to first get the political / organizational aspects out of the way), you can find a curated list of verified testdata here: https://github.com/eu-digital-green-certificates/dcc-quality-assurance and a more extensive (but possibly not 100% conforming to the spec) collection here: https://github.com/eu-digital-green-certificates/dgc-testdata to test against your system.

**Comment by SonVuBao** [comment]
Hi Daniel,

Thank you so much for your quick reply.

If it is possible, could you help me in the getting in touch with the European Commission. Thank you in advanced.

Regarding the technical side, we have been able to test the data with our developed application. However, we haven't been able to test the connection between our system and the gateway. Do you have any test dgc-gateway that we can try to connect and test our application.

**Comment by daniel-eder** [comment]
Regarding contact : please send me an e-mail at daniel.eder@magenta.at, I'll reply with further steps

**Comment by daniel-eder** [comment]
Regarding the gateway, https://github.com/eu-digital-green-certificates/dgc-participating-countries/blob/main/gateway/OnboardingChecklist.md has the links for the test environments, however being unlocked there still depends on prior agreement with the European Commission.

**Comment by daniel-eder** [comment]
Closing this & continuing via e-mail
