### ISSUE TITLE
Swagger UI headers

### ISSUE THREAD

**Issue by iliecirciumaru** [eu-digital-green-certificates/dgc-gateway#62]
## Current Implementation
In current implementation, it is not possible to send calls from Swagger UI because one can't provide `authentication headers`: `X-SSL-Client-SHA256` and `X-SSL-Client-DN`

## Suggested Enhancement
Add possibility to specify in Swagger UI these headers

## Expected Benefits
Swagger UI becomes more useful.

## Who should do it
I am happy to create PR if you believe it is a useful feature

**Comment by f11h** [comment]
Hi @iliecirciumaru,

yes this currently a "pain point". I do not want to add these headers to the swagger document because it could/would lead other developers to always send these headers (even in real deployed instance)

As long as the Swagger Doc is created programmatically we maybe could find a way to add these headers only when a specific profile (e.g. "dev") is active.
This would enable the usage of Try-Out feature on local deployments.

**Comment by f11h** [comment]
I have found another way to realize this. Please check the branch ```swagger-ui-auth-header``` and activate the Spring-Profile ```local``` then a "authorize" field should appear which accepts the two headers.

**Comment by f11h** [comment]
I've created a PR for this branch. This ticket will be closed as soon as the PR is merged.
