### ISSUE TITLE
What is the logic behind `normalizeCertificateHash` function?

### ISSUE THREAD

**Issue by quapka** [eu-digital-green-certificates/dgc-gateway#99]
* Source File: dgc-gateway/src/main/java/eu/europa/ec/dgc/gateway/restapi/filter/CertificateAuthenticationFilter.java
* Line(s): 84-120
* Question: What is the logic behind [`normalizeCertificateHash`](https://github.com/eu-digital-green-certificates/dgc-gateway/blob/1ebe5ad80506da34abf96f4cf763c356384e3c71/src/main/java/eu/europa/ec/dgc/gateway/restapi/filter/CertificateAuthenticationFilter.java#L84) function?

Rather than normalization, it looks like it performs some type of guesswork to end up with _a hash_ that is then used (in [`doFilterInternal`](https://github.com/eu-digital-green-certificates/dgc-gateway/blob/1ebe5ad80506da34abf96f4cf763c356384e3c71/src/main/java/eu/europa/ec/dgc/gateway/restapi/filter/CertificateAuthenticationFilter.java#L123)) to fetch client (!) certificate from the database to perform an authentication. What am I missing? :slightly_smiling_face:

**Comment by f11h** [comment]
Hi @quapka ,

we had to implement the AuthenticationFilter in this way because we will get the certificate thumbprint/hash in production environment passed as a HTTP-Header and URL encoded. In the past this wasn't a stable behaviour of the LoadBalancer so this was one step for more robustness.

Also for local development/testing it is rather uncomfortable to always URL Encode these parameters.

But as I can see we have also this beautiful "length == 63"-Feature in place. I will propose a PR to replace this one also with Bouncycastle HEX parser.
